import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppLayout } from "@/components/AppLayout";
import {
  Navbar,
  NavbarBrand,
  NavbarContent,
  NavbarItem,
  NavbarMenu,
  NavbarMenuItem,
} from "@nextui-org/navbar";
import { Button } from "@nextui-org/button";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Studyswipe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased light`}
      >
        <Navbar className="border-b-1 border-neutral-200">
          <NavbarBrand>
            <div className="flex gap-2 items-center">
              <Image src={"/icon-svg.svg"} width={36} height={36} alt="App icon"/>
              <span className="font-semibold">Studyswipe</span>
            </div>
          </NavbarBrand>
          <NavbarContent justify="center">
            <NavbarItem>
              <Link href="/decks" color="foreground">
                My decks
              </Link>
            </NavbarItem>
          </NavbarContent>
        </Navbar>
        <AppLayout>
          <main className="w-full max-w-screen-lg mx-auto px-6 py-6">
            {children}
          </main>
        </AppLayout>
      </body>
    </html>
  );
}
